syntax = "proto2";

package Messages;

message UpdateDataMessage {
    optional NewDeviceData new_device_data = 1;
    optional DeviceMeasurement device_measurement = 2;
}

message NewDeviceData {
    enum DeviceType {
        LIGHT       = 1;
        TEMPERATURE = 2;
    }

    required int32 id = 1;
    required DeviceType type = 2;
}

message DeviceMeasurement {
    required int32 id = 1;
    optional LightDeviceMeasurement light_device_measurement = 2;
    optional TemperatureDeviceMeasurement temperature_device_measurement = 3;
}

message LightDeviceMeasurement {
    required string brightness = 1;
}

message TemperatureDeviceMeasurement {
    required int32 temperature = 1;
}

message ChangeDataMessage {
    optional ChangeTemperature change_temperature = 2;
    optional ChangeLight change_light = 3;
}

message ChangeTemperature {
    optional DecreaseTemperature decrease_temperature = 1;
    optional IncreaseTemperature increase_temperature = 2;
}

message ChangeLight {
    optional LightOn light_on = 1;
    optional LightHalf light_half = 2;
    optional LightOff light_off = 3;
}

message DecreaseTemperature {
    required int32 id = 1;
}

message IncreaseTemperature {
    required int32 id = 1;
}

message LightOn {
    required int32 id = 1;
}

message LightHalf {
    required int32 id = 1;
}

message LightOff {
    required int32 id = 1;
}